title: Where distant light meets haunting beauty, I am capturing it one frame at a time.
author: Thanos Tserpelis
email: XXX@XXX.com
description: >-
  About me: Just an amateur astrophotographer taking pictures of the beautiful cosmos with a Seestar S50.

social:
  instagram: thanasis_twice

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
